### ISSUE TITLE
Deal with simulator pausing

### ISSUE THREAD

**Issue by ptsmonteiro** [xairline/zon#11]
- [x] do not run state machine/POS report when paused
- [ ] use simulator time not real time

**Comment by zodiac1214** [comment]
Note: sim/time/paused returns if sim is paused. in that case, do not send dataref from server side to client side

**Comment by ptsmonteiro** [comment]
This means also take into account times as simulator times and not real time.

**Comment by zodiac1214** [comment]
@ptsmonteiro what do you think on using `Hobbs meter` here?

**Comment by zodiac1214** [comment]
- [ ] do not run state machine/POS report when paused
- [ ] use simulator time not real time

**Comment by ptsmonteiro** [comment]
> 
> 
> @ptsmonteiro what do you think on using `Hobbs meter` here?

sim/time/hobbs_time counts when the aircraft is energized. I don't think that's what we want.

I think that times out/off/on/in can be taken from sim/time/zulu_time_sec but, due to the possibility of using pause and/or time acceleration, **block and flight times should be calculated from sim/time/total_flight_time**. 

What do you think?
