### ISSUE TITLE
Flight state after arrival at gate

### ISSUE THREAD

**Issue by ptsmonteiro** [xairline/zon#19]
After arrival at the gate at YPPH:

Client:
![image](https://user-images.githubusercontent.com/480012/142068400-37c636c4-54f5-414e-8474-e8bfcfcfd4ef.png)

Zon:
![image](https://user-images.githubusercontent.com/480012/142068518-d273e81f-3bbf-4b80-a0fe-4bba2b686a91.png)

Shoudn't we have an empty destination airport?

Should we have logic to try to understand if this is the end of the previous flight or the beginning of a new one?

**Comment by zodiac1214** [comment]
i think the idea is that, after a flight, i should show then landing analysis (and whatever other analysis in the future) then the app is reset to a state that you can fly another flight. I forget to show the analysis and it makes you feel it's gone ... i will fix this tonight :)

**Comment by ptsmonteiro** [comment]
This is not easy to tackle. Maybe we should only start tracking on ground movement/first engine start OR if the user clicks a button to start tracking before that.

**Comment by ptsmonteiro** [comment]
I think this is fixed now, can you confirm?
