### ISSUE TITLE
Problem with B777-F

### ISSUE THREAD

**Issue by Flugwitz** [xairline/zon#31]
Please can you Check the B777-F for The X plane 11 , There is not Activate as B77F 
For Zonexecutive it is a ZE-B77F  not B77L 
For Simbrief it`s o.k

**Comment by zodiac1214** [comment]
Is it ff777? They register as B77L in xplane…guess they reused 777200LR model so that's the problem. I can put a patch in the client that allows you to change it to B77F (need to confirm with ZE staff about the ICAO mapping tho)

**Comment by zodiac1214** [comment]
if it is FF777, that's a big there (i really want the 2.0 with all the bug fixes....). So i tried it, it is B77L and i go modifed their acf file and change it to B77F. now it is showing B77F in our new client now lol .... maybe you don't feel comforable to change that so i am still going to patch our client :) 
ToLiss had A21N as A321 now FF has B77F as B77L ... hope we don't grow this list too crazy ...

**Comment by zodiac1214** [comment]
@Flugwitz would be able to test https://github.com/xairline/zon/releases/tag/v0.1.6? it should now allow you to override B77L to B77F
