### ISSUE TITLE
Total flight time isn't correct

### ISSUE THREAD

**Issue by ptsmonteiro** [xairline/zon#6]
After completing a flight, my flight time of 0.4hrs (correctly displayed on the site) was displaying 0.07hrs on the client flight list.

**Comment by zodiac1214** [comment]
so i checked my flight history...it is showing 0.2 for one flight and API returns 
![image](https://user-images.githubusercontent.com/24868108/141807478-6ed26d73-299a-482f-a442-0d46a4c99cbe.png)
so i guess the site really means 0h:20m ??? i think it is ok to have h:m format but we should also fix our website ....
